# Generated by Django 5.2.3 on 2025-06-12 18:23

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='EncryptionJob',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('job_id', models.CharField(max_length=32, unique=True)),
                ('algorithm', models.CharField(choices=[('hill_cipher', 'Hill Cipher'), ('matrix_transform', 'Matrix Transformation'), ('advanced_matrix', 'Advanced Matrix Encryption')], max_length=50)),
                ('processing_method', models.CharField(max_length=20)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('processing', 'Processing'), ('completed', 'Completed'), ('failed', 'Failed')], default='pending', max_length=20)),
                ('input_type', models.CharField(max_length=20)),
                ('input_size', models.IntegerField()),
                ('matrix_size', models.IntegerField(default=8)),
                ('parallel_workers', models.IntegerField(default=1)),
                ('processing_time', models.FloatField(blank=True, null=True)),
                ('speedup_factor', models.FloatField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('error_message', models.TextField(blank=True)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='EncryptedFile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('original_filename', models.CharField(max_length=255)),
                ('encrypted_file', models.FileField(upload_to='encrypted_files/')),
                ('encryption_key_hash', models.CharField(default='', max_length=64)),
                ('file_size', models.IntegerField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('job', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='encryption_api.encryptionjob')),
            ],
        ),
    ]
