# Generated by Django 5.2.3 on 2025-06-12 18:23

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AlgorithmPerformance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('algorithm', models.CharField(max_length=50)),
                ('matrix_size', models.IntegerField()),
                ('avg_serial_time', models.FloatField()),
                ('avg_parallel_time', models.FloatField()),
                ('max_speedup', models.FloatField()),
                ('optimal_workers', models.IntegerField()),
                ('last_updated', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='SystemMetrics',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('cpu_usage', models.FloatField()),
                ('memory_usage', models.FloatField()),
                ('active_jobs', models.IntegerField()),
                ('total_requests', models.IntegerField()),
                ('average_response_time', models.FloatField()),
            ],
        ),
    ]
